using System;
using System.Collections.Generic;
using System.Globalization;
using System.IO;
using System.Reflection;

namespace RynthCore.Plugin.RynthAi;

/// <summary>One spell from ACECustom's spell catalog (Combat\SpellCatalog.tsv).</summary>
internal sealed class SpellCatalogEntry
{
    public int Id;
    public string Name = "";
    /// <summary>Spell level 1-8 (ACE Spell.Level from Power vs SpellFormula.MinPower).</summary>
    public int Level;
    /// <summary>Buff, Debuff, Heal, Harm, Neutral, Projectile or Utility.</summary>
    public string Effect = "";
    /// <summary>Self, Other, Item or Fellowship.</summary>
    public string Target = "";
    /// <summary>ACE SpellCategory: spells in one family don't stack, the highest power wins.</summary>
    public int FamilyId;
    public string FamilyName = "";
    public int Power;
    /// <summary>Seconds, or -1 for spells without a duration.</summary>
    public int DurationSec;
    /// <summary>Creature Enchantment, Life Magic, Item Enchantment, War Magic or Void Magic.</summary>
    public string School = "";
    public int Mana;
    public string Description = "";

    public bool IsBuff => Effect.Equals("Buff", StringComparison.OrdinalIgnoreCase);
    public bool IsSelf => Target.Equals("Self", StringComparison.OrdinalIgnoreCase);
    public bool IsItemTarget => Target.Equals("Item", StringComparison.OrdinalIgnoreCase);
}

/// <summary>
/// ACECustom's spell catalog (generated by Tools\Generate-SpellCatalog.ps1 from ACECustom
/// Reports\SpellCatalog-Full.csv). It is the spell list of the Spells window and buff profiles:
/// level, school, Self/Other/Item target and spell family per spell id.
/// </summary>
internal static class SpellCatalog
{
    private const string ResourceName = "RynthCore.Plugin.RynthAi.Combat.SpellCatalog.tsv";

    /// <summary>The five magic schools, in the order the UI lists them.</summary>
    public static readonly string[] Schools =
    {
        "Creature Enchantment", "Life Magic", "Item Enchantment", "War Magic", "Void Magic",
    };

    private static readonly object Gate = new();
    private static List<SpellCatalogEntry> _all = new();
    private static Dictionary<int, SpellCatalogEntry> _byId = new();
    private static Dictionary<int, List<SpellCatalogEntry>> _byFamily = new();
    private static Dictionary<string, SpellCatalogEntry> _byName = new(StringComparer.OrdinalIgnoreCase);
    private static string[] _effects = Array.Empty<string>();

    public static bool IsLoaded => _all.Count > 0;
    public static IReadOnlyList<SpellCatalogEntry> All => _all;

    /// <summary>Distinct effect types present in the catalog (Buff, Debuff, ...), sorted.</summary>
    public static IReadOnlyList<string> Effects => _effects;

    /// <summary>Loads the embedded catalog once. Safe to call repeatedly.</summary>
    public static void EnsureLoaded(Action<string>? log = null)
    {
        if (IsLoaded) return;
        lock (Gate)
        {
            if (IsLoaded) return;
            try
            {
                using Stream? stream = Assembly.GetExecutingAssembly().GetManifestResourceStream(ResourceName);
                if (stream == null)
                {
                    log?.Invoke($"[RynthAi] Spell catalog resource missing: {ResourceName}");
                    return;
                }
                using var reader = new StreamReader(stream, detectEncodingFromByteOrderMarks: true);
                LoadFrom(reader);
            }
            catch (Exception ex)
            {
                log?.Invoke($"[RynthAi] Spell catalog load failed: {ex.Message}");
            }
        }
    }

    /// <summary>Parses catalog lines (tests feed their own). Replaces anything loaded before.</summary>
    public static void LoadFrom(TextReader reader)
    {
        var all = new List<SpellCatalogEntry>(6400);
        string? line;
        while ((line = reader.ReadLine()) != null)
        {
            if (line.Length == 0 || line[0] == '#') continue;
            string[] c = line.Split('\t');
            if (c.Length < 11 || !int.TryParse(c[0], NumberStyles.Integer, CultureInfo.InvariantCulture, out int id))
                continue;
            all.Add(new SpellCatalogEntry
            {
                Id = id,
                Name = c[1],
                Level = ParseInt(c[2]),
                Effect = c[3],
                Target = c[4],
                FamilyId = ParseInt(c[5]),
                FamilyName = c[6],
                Power = ParseInt(c[7]),
                DurationSec = ParseInt(c[8]),
                School = c[9],
                Mana = ParseInt(c[10]),
                Description = c.Length > 11 ? c[11] : "",
            });
        }

        var byId = new Dictionary<int, SpellCatalogEntry>(all.Count);
        var byFamily = new Dictionary<int, List<SpellCatalogEntry>>();
        var byName = new Dictionary<string, SpellCatalogEntry>(StringComparer.OrdinalIgnoreCase);
        var effects = new SortedSet<string>(StringComparer.OrdinalIgnoreCase);
        foreach (var e in all)
        {
            byId[e.Id] = e;
            if (e.FamilyId != 0)
            {
                if (!byFamily.TryGetValue(e.FamilyId, out var list)) byFamily[e.FamilyId] = list = new List<SpellCatalogEntry>();
                list.Add(e);
            }
            // Several ids share a name (e.g. mastery lines); the lowest id is the canonical one.
            byName.TryAdd(e.Name, e);
            if (e.Effect.Length > 0) effects.Add(e.Effect);
        }

        lock (Gate)
        {
            _byId = byId;
            _byFamily = byFamily;
            _byName = byName;
            _effects = new List<string>(effects).ToArray();
            _all = all;
        }
    }

    public static SpellCatalogEntry? Get(int spellId) =>
        _byId.TryGetValue(spellId, out var e) ? e : null;

    public static SpellCatalogEntry? GetByName(string name) =>
        !string.IsNullOrEmpty(name) && _byName.TryGetValue(name, out var e) ? e : null;

    /// <summary>Every spell in a family (empty when the family is unknown).</summary>
    public static IReadOnlyList<SpellCatalogEntry> Family(int familyId) =>
        _byFamily.TryGetValue(familyId, out var list) ? list : (IReadOnlyList<SpellCatalogEntry>)Array.Empty<SpellCatalogEntry>();

    /// <summary>
    /// True for an Item Enchantment buff: it lands on armor or a weapon, not on the player,
    /// so its timer can only come from the cast's chat line. Unknown names are false.
    /// </summary>
    public static bool IsItemSchoolBuff(string name)
    {
        var e = GetByName(name);
        return e != null && e.IsBuff && e.School.Equals("Item Enchantment", StringComparison.OrdinalIgnoreCase);
    }

    /// <summary>Casting skill for a school name; CreatureEnchantment when unrecognised.</summary>
    public static AcSkillType SkillForSchool(string school) => school switch
    {
        "Life Magic" => AcSkillType.LifeMagic,
        "Item Enchantment" => AcSkillType.ItemEnchantment,
        "War Magic" => AcSkillType.WarMagic,
        "Void Magic" => AcSkillType.VoidMagic,
        _ => AcSkillType.CreatureEnchantment,
    };

    /// <summary>Short school label for narrow table columns.</summary>
    public static string ShortSchool(string school) => school switch
    {
        "Creature Enchantment" => "Creature",
        "Life Magic" => "Life",
        "Item Enchantment" => "Item",
        "War Magic" => "War",
        "Void Magic" => "Void",
        _ => school,
    };

    private static readonly string[] TierSuffixes = { " VIII", " VII", " VI", " IV", " V", " III", " II", " I" };

    /// <summary>
    /// A spell name without its tier: "Strength Self VI" → "Strength Self",
    /// "Incantation of Blade Bane" → "Blade Bane", "Aura of Blood Drinker Self III" →
    /// "Blood Drinker Self", "Impenetrability Incantation" → "Impenetrability".
    /// Names without a tier (lore spells) come back unchanged.
    /// </summary>
    public static string StripTier(string name)
    {
        string n = (name ?? "").Trim();
        if (n.StartsWith("Incantation of ", StringComparison.OrdinalIgnoreCase)) n = n.Substring("Incantation of ".Length);
        if (n.StartsWith("Aura of ", StringComparison.OrdinalIgnoreCase)) n = n.Substring("Aura of ".Length);
        if (n.EndsWith(" Incantation", StringComparison.OrdinalIgnoreCase)) n = n.Substring(0, n.Length - " Incantation".Length);
        foreach (string s in TierSuffixes)
        {
            if (n.EndsWith(s, StringComparison.Ordinal))
            {
                n = n.Substring(0, n.Length - s.Length);
                break;
            }
        }
        return n.Trim();
    }

    /// <summary>
    /// The buffing key for a spell: the base name buffing resolves to the best tier the character
    /// knows ("Strength Self"). A Self or Item spell is its own ladder; for an Other spell
    /// (including lore and server-custom names like "Might of the Lugians") the family's lowest
    /// Self ladder is used, then its Item ladder, so buffing casts the self-castable form.
    /// </summary>
    public static string BuffKeyFor(SpellCatalogEntry e)
    {
        if (e.IsSelf || e.IsItemTarget) return StripTier(e.Name);

        SpellCatalogEntry? self = null, item = null;
        foreach (var m in Family(e.FamilyId))
        {
            if (!m.IsBuff) continue;
            if (m.IsSelf && (self == null || m.Level < self.Level || (m.Level == self.Level && m.Id < self.Id))) self = m;
            else if (m.IsItemTarget && (item == null || m.Level < item.Level || (m.Level == item.Level && m.Id < item.Id))) item = m;
        }
        return StripTier((self ?? item ?? e).Name);
    }

    private static int ParseInt(string s) =>
        int.TryParse(s, NumberStyles.Integer, CultureInfo.InvariantCulture, out int v) ? v : 0;
}
