// Generated from the enum definitions UtilityBelt scripts use (AC protocol enums, whose names
// and values match ACE's, and UtilityBelt's scripting enums): names and numbers only.
// Regenerate rather than edit by hand. The property-id enums RynthLua already had (IntId,
// BoolId, StringId), ObjectClass, SkillId, AttributeId, VitalId, CombatMode and ChatType
// live in LibraryEnums.cs / LuaEnums.cs.
namespace RynthCore.Plugin.RynthLua;

internal static class LuaEnumData
{
    /// <summary>(enum name, is a flags enum, members in declaration order).</summary>
    public static readonly (string Name, bool Flags, (string, long)[] Members)[] All =
    {
        ("AmmoType", false, new (string, long)[]
        {
            ("ThrownWeapon", 0), ("Arrow", 1), ("Bolt", 2), ("Dart", 4),
        }),
        ("AttackHeight", false, new (string, long)[]
        {
            ("High", 1), ("Medium", 2), ("Low", 3),
        }),
        ("CharacterOptions1", true, new (string, long)[]
        {
            ("u_0x00000001", 1), ("u_0x00000002", 2), ("u_0x00000004", 4), ("u_0x00000008", 8), ("u_0x00000010", 16),
            ("u_0x00000020", 32), ("u_0x00000040", 64), ("u_0x00000080", 128), ("u_0x00000100", 256),
            ("u_0x00000200", 512), ("u_0x00000400", 1024), ("u_0x00000800", 2048), ("u_0x00001000", 4096),
            ("u_0x00002000", 8192), ("u_0x00004000", 16384), ("u_0x00008000", 32768), ("u_0x00010000", 65536),
            ("u_0x00020000", 131072), ("u_0x00040000", 262144), ("u_0x00080000", 524288), ("u_0x00100000", 1048576),
            ("u_0x00200000", 2097152), ("u_0x00400000", 4194304), ("u_0x00800000", 8388608),
            ("u_0x01000000", 16777216), ("u_0x02000000", 33554432), ("u_0x04000000", 67108864),
            ("u_0x08000000", 134217728), ("u_0x10000000", 268435456), ("u_0x20000000", 536870912),
            ("u_0x40000000", 1073741824), ("u_0x80000000", 2147483648),
        }),
        ("CharacterOptions2", true, new (string, long)[]
        {
            ("u_0x00000001", 1), ("u_0x00000002", 2), ("u_0x00000004", 4), ("u_0x00000008", 8), ("u_0x00000010", 16),
            ("u_0x00000020", 32), ("u_0x00000040", 64), ("u_0x00000080", 128), ("u_0x00000100", 256),
            ("u_0x00000200", 512), ("u_0x00000400", 1024), ("u_0x00000800", 2048), ("u_0x00002000", 8192),
            ("u_0x00004000", 16384), ("u_0x00008000", 32768), ("u_0x00010000", 65536), ("u_0x00020000", 131072),
            ("u_0x00040000", 262144),
        }),
        ("ContainerProperties", false, new (string, long)[]
        {
            ("None", 0), ("Container", 1), ("Foci", 2),
        }),
        ("CoverageMask", true, new (string, long)[]
        {
            ("UpperLegsUnderwear", 2), ("LowerLegsUnderwear", 4), ("ChestUnderwear", 8), ("AbdomenUnderwear", 16),
            ("UpperArmsUnderwear", 32), ("LowerArmsUnderwear", 64), ("UpperLegs", 256), ("LowerLegs", 512),
            ("Chest", 1024), ("Abdomen", 2048), ("UpperArms", 4096), ("LowerArms", 8192), ("Head", 16384),
            ("Hands", 32768), ("Feet", 65536),
        }),
        ("CreatureType", false, new (string, long)[]
        {
            ("Invalid", 0), ("Olthoi", 1), ("Banderling", 2), ("Drudge", 3), ("Mosswart", 4), ("Lugian", 5),
            ("Tumerok", 6), ("Mite", 7), ("Tusker", 8), ("PhyntosWasp", 9), ("Rat", 10), ("Auroch", 11), ("Cow", 12),
            ("Golem", 13), ("Undead", 14), ("Gromnie", 15), ("Reedshark", 16), ("Armoredillo", 17), ("Fae", 18),
            ("Virindi", 19), ("Wisp", 20), ("Knathtead", 21), ("Shadow", 22), ("Mattekar", 23), ("Mumiyah", 24),
            ("Rabbit", 25), ("Sclavus", 26), ("ShallowsShark", 27), ("Monouga", 28), ("Zefir", 29), ("Skeleton", 30),
            ("Human", 31), ("Shreth", 32), ("Chittick", 33), ("Moarsman", 34), ("OlthoiLarvae", 35), ("Slithis", 36),
            ("Deru", 37), ("FireElemental", 38), ("Snowman", 39), ("Unknown", 40), ("Bunny", 41),
            ("LightningElemental", 42), ("Rockslide", 43), ("Grievver", 44), ("Niffis", 45), ("Ursuin", 46),
            ("Crystal", 47), ("HollowMinion", 48), ("Scarecrow", 49), ("Idol", 50), ("Empyrean", 51),
            ("Hopeslayer", 52), ("Doll", 53), ("Marionette", 54), ("Carenzi", 55), ("Siraluun", 56),
            ("AunTumerok", 57), ("HeaTumerok", 58), ("Simulacrum", 59), ("AcidElemental", 60),
            ("FrostElemental", 61), ("Elemental", 62), ("Statue", 63), ("Wall", 64), ("AlteredHuman", 65),
            ("Device", 66), ("Harbinger", 67), ("DarkSarcophagus", 68), ("Chicken", 69), ("GotrokLugian", 70),
            ("Margul", 71), ("BleachedRabbit", 72), ("NastyRabbit", 73), ("GrimacingRabbit", 74), ("Burun", 75),
            ("Target", 76), ("Ghost", 77), ("Fiun", 78), ("Eater", 79), ("Penguin", 80), ("Ruschk", 81),
            ("Thrungus", 82), ("ViamontianKnight", 83), ("Remoran", 84), ("Swarm", 85), ("Moar", 86),
            ("EnchantedArms", 87), ("Sleech", 88), ("Mukkir", 89), ("Merwart", 90), ("Food", 91),
            ("ParadoxOlthoi", 92), ("Harvest", 93), ("Energy", 94), ("Apparition", 95), ("Aerbax", 96),
            ("Touched", 97), ("BlightedMoarsman", 98), ("GearKnight", 99), ("Gurog", 100), ("Anekshay", 101),
        }),
        ("DamageType", true, new (string, long)[]
        {
            ("Slashing", 1), ("Piercing", 2), ("Bludgeoning", 4), ("Cold", 8), ("Fire", 16), ("Acid", 32),
            ("Electric", 64),
        }),
        ("DataId", false, new (string, long)[]
        {
            ("Undef", 0), ("Setup", 1), ("MotionTable", 2), ("SoundTable", 3), ("CombatTable", 4),
            ("QualityFilter", 5), ("PaletteBase", 6), ("ClothingBase", 7), ("Icon", 8), ("EyesTexture", 9),
            ("NoseTexture", 10), ("MouthTexture", 11), ("DefaultEyesTexture", 12), ("DefaultNoseTexture", 13),
            ("DefaultMouthTexture", 14), ("HairPalette", 15), ("EyesPalette", 16), ("SkinPalette", 17),
            ("HeadObject", 18), ("ActivationAnimation", 19), ("InitMotion", 20), ("ActivationSound", 21),
            ("PhysicsEffectTable", 22), ("UseSound", 23), ("UseTargetAnimation", 24),
            ("UseTargetSuccessAnimation", 25), ("UseTargetFailureAnimation", 26), ("UseUserAnimation", 27),
            ("Spell", 28), ("SpellComponent", 29), ("PhysicsScript", 30), ("LinkedPortalOne", 31),
            ("WieldedTreasureType", 32), ("UnknownGuessedname", 33), ("UnknownGuessedname2", 34),
            ("DeathTreasureType", 35), ("MutateFilter", 36), ("ItemSkillLimit", 37), ("UseCreateItem", 38),
            ("DeathSpell", 39), ("VendorsClassId", 40), ("ItemSpecializedOnly", 41), ("HouseId", 42),
            ("AccountHouseId", 43), ("RestrictionEffect", 44), ("CreationMutationFilter", 45),
            ("TsysMutationFilter", 46), ("LastPortal", 47), ("LinkedPortalTwo", 48), ("OriginalPortal", 49),
            ("IconOverlay", 50), ("IconOverlaySecondary", 51), ("IconUnderlay", 52),
            ("AugmentationMutationFilter", 53), ("AugmentationEffect", 54), ("ProcSpell", 55),
            ("AugmentationCreateItem", 56), ("AlternateCurrency", 57), ("BlueSurgeSpell", 58),
            ("YellowSurgeSpell", 59), ("RedSurgeSpell", 60), ("OlthoiDeathTreasureType", 61),
        }),
        ("EnchantmentFlags", false, new (string, long)[]
        {
            ("Undef", 0), ("Attribute", 1), ("Attribute2nd", 2), ("Int", 4), ("Float", 8), ("Skill", 16),
            ("BodyDamageValue", 32), ("BodyDamageVariance", 64), ("BodyArmorValue", 128), ("SingleStat", 4096),
            ("MultipleStat", 8192), ("Multiplicative", 16384), ("Additive", 32768), ("AttackSkills", 65536),
            ("DefenseSkills", 131072), ("Multiplicative_Degrade", 1048576), ("Additive_Degrade", 2097152),
            ("Vitae", 8388608), ("Cooldown", 16777216), ("Beneficial", 33554432), ("StatTypes", 255),
        }),
        ("EndTradeReason", false, new (string, long)[]
        {
            ("Normal", 0), ("EnteredCombat", 2), ("Cancelled", 81),
        }),
        ("EquipMask", true, new (string, long)[]
        {
            ("None", 0), ("Head", 1), ("ChestUnderwear", 2), ("AbdomenUnderwear", 4), ("UpperArmsUnderwear", 8),
            ("LowerArmsUnderwear", 16), ("Hands", 32), ("UpperLegsUnderwear", 64), ("LowerLegsUnderwear", 128),
            ("Feet", 256), ("Chest", 512), ("Abdomen", 1024), ("UpperArms", 2048), ("LowerArms", 4096),
            ("UpperLegs", 8192), ("LowerLegs", 16384), ("Necklace", 32768), ("RightBracelet", 65536),
            ("LeftBracelet", 131072), ("RightRing", 262144), ("LeftRing", 524288), ("MeleeWeapon", 1048576),
            ("Shield", 2097152), ("MissileWeapon", 4194304), ("Ammunition", 8388608), ("Wand", 16777216),
            ("Cloak", 134217728), ("Trinket", 67108864), ("BlueAetheria", 268435456), ("YellowAetheria", 536870912),
            ("RedAetheria", 1073741824),
        }),
        ("FloatId", false, new (string, long)[]
        {
            ("Undef", 0), ("HeartbeatInterval", 1), ("HeartbeatTimestamp", 2), ("HealthRate", 3), ("StaminaRate", 4),
            ("ManaRate", 5), ("HealthUponResurrection", 6), ("StaminaUponResurrection", 7),
            ("ManaUponResurrection", 8), ("StartTime", 9), ("StopTime", 10), ("ResetInterval", 11), ("Shade", 12),
            ("ArmorModVsSlash", 13), ("ArmorModVsPierce", 14), ("ArmorModVsBludgeon", 15), ("ArmorModVsCold", 16),
            ("ArmorModVsFire", 17), ("ArmorModVsAcid", 18), ("ArmorModVsElectric", 19), ("CombatSpeed", 20),
            ("WeaponLength", 21), ("DamageVariance", 22), ("CurrentPowerMod", 23), ("AccuracyMod", 24),
            ("StrengthMod", 25), ("MaximumVelocity", 26), ("RotationSpeed", 27), ("MotionTimestamp", 28),
            ("WeaponDefense", 29), ("WimpyLevel", 30), ("VisualAwarenessRange", 31), ("AuralAwarenessRange", 32),
            ("PerceptionLevel", 33), ("PowerupTime", 34), ("MaxChargeDistance", 35), ("ChargeSpeed", 36),
            ("BuyPrice", 37), ("SellPrice", 38), ("DefaultScale", 39), ("LockpickMod", 40),
            ("RegenerationInterval", 41), ("RegenerationTimestamp", 42), ("GeneratorRadius", 43), ("TimeToRot", 44),
            ("DeathTimestamp", 45), ("PkTimestamp", 46), ("VictimTimestamp", 47), ("LoginTimestamp", 48),
            ("CreationTimestamp", 49), ("MinimumTimeSincePk", 50), ("DeprecatedHousekeepingPriority", 51),
            ("AbuseLoggingTimestamp", 52), ("LastPortalTeleportTimestamp", 53), ("UseRadius", 54),
            ("HomeRadius", 55), ("ReleasedTimestamp", 56), ("MinHomeRadius", 57), ("Facing", 58),
            ("ResetTimestamp", 59), ("LogoffTimestamp", 60), ("EconRecoveryInterval", 61), ("WeaponOffense", 62),
            ("DamageMod", 63), ("ResistSlash", 64), ("ResistPierce", 65), ("ResistBludgeon", 66), ("ResistFire", 67),
            ("ResistCold", 68), ("ResistAcid", 69), ("ResistElectric", 70), ("ResistHealthBoost", 71),
            ("ResistStaminaDrain", 72), ("ResistStaminaBoost", 73), ("ResistManaDrain", 74), ("ResistManaBoost", 75),
            ("Translucency", 76), ("PhysicsScriptIntensity", 77), ("Friction", 78), ("Elasticity", 79),
            ("AiUseMagicDelay", 80), ("ItemMinSpellcraftMod", 81), ("ItemMaxSpellcraftMod", 82),
            ("ItemRankProbability", 83), ("Shade2", 84), ("Shade3", 85), ("Shade4", 86), ("ItemEfficiency", 87),
            ("ItemManaUpdateTimestamp", 88), ("SpellGestureSpeedMod", 89), ("SpellStanceSpeedMod", 90),
            ("AllegianceAppraisalTimestamp", 91), ("PowerLevel", 92), ("AccuracyLevel", 93), ("AttackAngle", 94),
            ("AttackTimestamp", 95), ("CheckpointTimestamp", 96), ("SoldTimestamp", 97), ("UseTimestamp", 98),
            ("UseLockTimestamp", 99), ("HealkitMod", 100), ("FrozenTimestamp", 101), ("HealthRateMod", 102),
            ("AllegianceSwearTimestamp", 103), ("ObviousRadarRange", 104), ("HotspotCycleTime", 105),
            ("HotspotCycleTimeVariance", 106), ("SpamTimestamp", 107), ("SpamRate", 108),
            ("BondWieldedTreasure", 109), ("BulkMod", 110), ("SizeMod", 111), ("GagTimestamp", 112),
            ("GeneratorUpdateTimestamp", 113), ("DeathSpamTimestamp", 114), ("DeathSpamRate", 115),
            ("WildAttackProbability", 116), ("FocusedProbability", 117), ("CrashAndTurnProbability", 118),
            ("CrashAndTurnRadius", 119), ("CrashAndTurnBias", 120), ("GeneratorInitialDelay", 121),
            ("AiAcquireHealth", 122), ("AiAcquireStamina", 123), ("AiAcquireMana", 124), ("ResistHealthDrain", 125),
            ("LifestoneProtectionTimestamp", 126), ("AiCounteractEnchantment", 127), ("AiDispelEnchantment", 128),
            ("TradeTimestamp", 129), ("AiTargetedDetectionRadius", 130), ("EmotePriority", 131),
            ("LastTeleportStartTimestamp", 132), ("EventSpamTimestamp", 133), ("EventSpamRate", 134),
            ("InventoryOffset", 135), ("CriticalMultiplier", 136), ("ManaStoneDestroyChance", 137),
            ("SlayerDamageBonus", 138), ("AllegianceInfoSpamTimestamp", 139), ("AllegianceInfoSpamRate", 140),
            ("NextSpellcastTimestamp", 141), ("AppraisalRequestedTimestamp", 142),
            ("AppraisalHeartbeatDueTimestamp", 143), ("ManaConversionMod", 144), ("LastPkAttackTimestamp", 145),
            ("FellowshipUpdateTimestamp", 146), ("CriticalFrequency", 147), ("LimboStartTimestamp", 148),
            ("WeaponMissileDefense", 149), ("WeaponMagicDefense", 150), ("IgnoreShield", 151),
            ("ElementalDamageMod", 152), ("StartMissileAttackTimestamp", 153), ("LastRareUsedTimestamp", 154),
            ("IgnoreArmor", 155), ("ProcSpellRate", 156), ("ResistanceModifier", 157),
            ("AllegianceGagTimestamp", 158), ("AbsorbMagicDamage", 159), ("CachedMaxAbsorbMagicDamage", 160),
            ("GagDuration", 161), ("AllegianceGagDuration", 162), ("GlobalXpMod", 163), ("HealingModifier", 164),
            ("ArmorModVsNether", 165), ("ResistNether", 166), ("CooldownDuration", 167), ("WeaponAuraOffense", 168),
            ("WeaponAuraDefense", 169), ("WeaponAuraElemental", 170), ("WeaponAuraManaConv", 171),
        }),
        ("Gender", false, new (string, long)[]
        {
            ("Invalid", 0), ("Male", 1), ("Female", 2),
        }),
        ("HeritageGroup", false, new (string, long)[]
        {
            ("Invalid", 0), ("Aluvian", 1), ("Gharundim", 2), ("Sho", 3), ("Viamontian", 4), ("Shadowbound", 5),
            ("Gearknight", 6), ("Tumerok", 7), ("Lugian", 8), ("Empyrean", 9), ("Penumbraen", 10), ("Undead", 11),
            ("Olthoi", 12), ("OlthoiAcid", 13),
        }),
        ("IconHighlight", true, new (string, long)[]
        {
            ("Invalid", 0), ("Magical", 1), ("Poisoned", 2), ("BoostHealth", 4), ("BoostMana", 8),
            ("BoostStamina", 16), ("Fire", 32), ("Lightning", 64), ("Frost", 128), ("Acid", 256),
            ("Bludgeoning", 512), ("Slashing", 1024), ("Piercing", 2048), ("Nether", 4096),
        }),
        ("InstanceId", false, new (string, long)[]
        {
            ("Undef", 0), ("Owner", 1), ("Container", 2), ("Wielder", 3), ("Freezer", 4), ("Viewer", 5),
            ("Generator", 6), ("Scribe", 7), ("CurrentCombatTarget", 8), ("CurrentEnemy", 9),
            ("ProjectileLauncher", 10), ("CurrentAttacker", 11), ("CurrentDamager", 12), ("CurrentFollowTarget", 13),
            ("CurrentAppraisalTarget", 14), ("CurrentFellowshipAppraisalTarget", 15), ("ActivationTarget", 16),
            ("Creator", 17), ("Victim", 18), ("Killer", 19), ("Vendor", 20), ("Customer", 21), ("Bonded", 22),
            ("Wounder", 23), ("Allegiance", 24), ("Patron", 25), ("Monarch", 26), ("CombatTarget", 27),
            ("HealthQueryTarget", 28), ("LastUnlocker", 29), ("CrashAndTurnTarget", 30), ("AllowedActivator", 31),
            ("HouseOwner", 32), ("House", 33), ("Slumlord", 34), ("ManaQueryTarget", 35), ("CurrentGame", 36),
            ("RequestedAppraisalTarget", 37), ("AllowedWielder", 38), ("AssignedTarget", 39), ("LimboSource", 40),
            ("Snooper", 41), ("TeleportedCharacter", 42), ("Pet", 43), ("PetOwner", 44), ("PetDevice", 45),
        }),
        ("Int64Id", false, new (string, long)[]
        {
            ("Undef", 0), ("TotalExperience", 1), ("AvailableExperience", 2), ("AugmentationCost", 3),
            ("ItemTotalXp", 4), ("ItemBaseXp", 5), ("AvailableLuminance", 6), ("MaximumLuminance", 7),
            ("InteractionReqs", 8),
        }),
        ("MagicSchool", false, new (string, long)[]
        {
            ("None", 0), ("WarMagic", 1), ("LifeMagic", 2), ("ItemEnchantment", 3), ("CreatureEnchantment", 4),
            ("VoidMagic", 5),
        }),
        ("MaterialType", false, new (string, long)[]
        {
            ("Ceramic", 1), ("Porcelain", 2), ("Linen", 4), ("Satin", 5), ("Silk", 6), ("Velvet", 7), ("Wool", 8),
            ("Agate", 10), ("Amber", 11), ("Amethyst", 12), ("Aquamarine", 13), ("Azurite", 14), ("BlackGarnet", 15),
            ("BlackOpal", 16), ("Bloodstone", 17), ("Carnelian", 18), ("Citrine", 19), ("Diamond", 20),
            ("Emerald", 21), ("FireOpal", 22), ("GreenGarnet", 23), ("GreenJade", 24), ("Hematite", 25),
            ("ImperialTopaz", 26), ("Jet", 27), ("LapisLazuli", 28), ("LavenderJade", 29), ("Malachite", 30),
            ("Moonstone", 31), ("Onyx", 32), ("Opal", 33), ("Peridot", 34), ("RedGarnet", 35), ("RedJade", 36),
            ("RoseQuartz", 37), ("Ruby", 38), ("Sapphire", 39), ("SmokeyQuartz", 40), ("Sunstone", 41),
            ("TigerEye", 42), ("Tourmaline", 43), ("Turquoise", 44), ("WhiteJade", 45), ("WhiteQuartz", 46),
            ("WhiteSapphire", 47), ("YellowGarnet", 48), ("YellowTopaz", 49), ("Zircon", 50), ("Ivory", 51),
            ("Leather", 52), ("ArmoredilloHide", 53), ("GromnieHide", 54), ("ReedSharkHide", 55), ("Brass", 57),
            ("Bronze", 58), ("Copper", 59), ("Gold", 60), ("Iron", 61), ("Pyreal", 62), ("Silver", 63),
            ("Steel", 64), ("Alabaster", 66), ("Granite", 67), ("Marble", 68), ("Obsidian", 69), ("Sandstone", 70),
            ("Serpentine", 71), ("Ebony", 73), ("Mahogany", 74), ("Oak", 75), ("Pine", 76), ("Teak", 77),
        }),
        ("MotionStance", false, new (string, long)[]
        {
            ("HandCombat", 60), ("NonCombat", 61), ("SwordCombat", 62), ("BowCombat", 63), ("SwordShieldCombat", 64),
            ("CrossbowCombat", 65), ("UnusedCombat", 66), ("SlingCombat", 67), ("TwoHandedSwordCombat", 68),
            ("TwoHandedStaffCombat", 69), ("DualWieldCombat", 70), ("ThrownWeaponCombat", 71), ("Magic", 73),
            ("BowNoAmmo", 232), ("CrossBowNoAmmo", 233), ("AtlatlCombat", 312), ("ThrownShieldCombat", 313),
        }),
        ("ObjectDescriptionFlag", true, new (string, long)[]
        {
            ("Openable", 1), ("Inscribable", 2), ("Stuck", 4), ("Player", 8), ("Attackable", 16),
            ("PlayerKiller", 32), ("HiddenAdmin", 64), ("UiHidden", 128), ("Book", 256), ("Vendor", 512),
            ("PkSwitch", 1024), ("NpkSwitch", 2048), ("Door", 4096), ("Corpse", 8192), ("LifeStone", 16384),
            ("Food", 32768), ("Healer", 65536), ("Lockpick", 131072), ("Portal", 262144), ("Admin", 1048576),
            ("FreePkStatus", 2097152), ("ImmuneCellRestrictions", 4194304), ("RequiresPackSlot", 8388608),
            ("Retained", 16777216), ("PkLiteStatus", 33554432), ("IncludesSecondHeader", 67108864),
            ("BindStone", 134217728), ("VolatileRare", 268435456), ("WieldOnUse", 536870912),
            ("WieldLeft", 1073741824),
        }),
        ("ObjectType", true, new (string, long)[]
        {
            ("MeleeWeapon", 1), ("Armor", 2), ("Clothing", 4), ("Jewelry", 8), ("Creature", 16), ("Food", 32),
            ("Money", 64), ("Misc", 128), ("MissileWeapon", 256), ("Container", 512), ("Useless", 1024),
            ("Gem", 2048), ("SpellComponents", 4096), ("Writable", 8192), ("Key", 16384), ("Caster", 32768),
            ("Portal", 65536), ("Lockable", 131072), ("PromissoryNote", 262144), ("ManaStone", 524288),
            ("Service", 1048576), ("MagicWieldable", 2097152), ("CraftCookingBase", 4194304),
            ("CraftAlchemyBase", 8388608), ("CraftFletchingBase", 33554432), ("CraftAlchemyIntermediate", 67108864),
            ("CraftFletchingIntermediate", 134217728), ("LifeStone", 268435456), ("TinkeringTool", 536870912),
            ("TinkeringMaterial", 1073741824), ("Gameboard", 2147483648),
        }),
        ("PhysicsState", true, new (string, long)[]
        {
            ("None", 0), ("Static", 1), ("Ethereal", 4), ("ReportCollision", 8), ("IgnoreCollision", 16),
            ("NoDraw", 32), ("Missle", 64), ("Pushable", 128), ("AlignPath", 256), ("PathClipped", 512),
            ("Gravity", 1024), ("LightingOn", 2048), ("ParticleEmitter", 4096), ("Hidden", 16384),
            ("ScriptedCollision", 32768), ("HasPhysicsBsp", 65536), ("Inelastic", 131072),
            ("HasDefaultAnim", 262144), ("HasDefaultScript", 524288), ("Cloaked", 1048576),
            ("ReportCollisionAsEnvironment", 2097152), ("EdgeSlide", 4194304), ("Sledding", 8388608),
            ("Frozen", 16777216),
        }),
        ("PlayScript", false, new (string, long)[]
        {
            ("Invalid", 0), ("Test1", 1), ("Test2", 2), ("Test3", 3), ("Launch", 4), ("Explode", 5),
            ("AttribUpRed", 6), ("AttribDownRed", 7), ("AttribUpOrange", 8), ("AttribDownOrange", 9),
            ("AttribUpYellow", 10), ("AttribDownYellow", 11), ("AttribUpGreen", 12), ("AttribDownGreen", 13),
            ("AttribUpBlue", 14), ("AttribDownBlue", 15), ("AttribUpPurple", 16), ("AttribDownPurple", 17),
            ("SkillUpRed", 18), ("SkillDownRed", 19), ("SkillUpOrange", 20), ("SkillDownOrange", 21),
            ("SkillUpYellow", 22), ("SkillDownYellow", 23), ("SkillUpGreen", 24), ("SkillDownGreen", 25),
            ("SkillUpBlue", 26), ("SkillDownBlue", 27), ("SkillUpPurple", 28), ("SkillDownPurple", 29),
            ("SkillDownBlack", 30), ("HealthUpRed", 31), ("HealthDownRed", 32), ("HealthUpBlue", 33),
            ("HealthDownBlue", 34), ("HealthUpYellow", 35), ("HealthDownYellow", 36), ("RegenUpRed", 37),
            ("RegenDownREd", 38), ("RegenUpBlue", 39), ("RegenDownBlue", 40), ("RegenUpYellow", 41),
            ("RegenDownYellow", 42), ("ShieldUpRed", 43), ("ShieldDownRed", 44), ("ShieldUpOrange", 45),
            ("ShieldDownOrange", 46), ("ShieldUpYellow", 47), ("ShieldDownYellow", 48), ("ShieldUpGreen", 49),
            ("ShieldDownGreen", 50), ("ShieldUpBlue", 51), ("ShieldDownBlue", 52), ("ShieldUpPurple", 53),
            ("ShieldDownPurple", 54), ("ShieldUpGrey", 55), ("ShieldDownGrey", 56), ("EnchantUpRed", 57),
            ("EnchantDownRed", 58), ("EnchantUpOrange", 59), ("EnchantDownOrange", 60), ("EnchantUpYellow", 61),
            ("EnchantDownYellow", 62), ("EnchantUpGreen", 63), ("EnchantDownGreen", 64), ("EnchantUpBlue", 65),
            ("EnchantDownBlue", 66), ("EnchantUpPurple", 67), ("EnchantDownPurple", 68), ("VitaeUpWhite", 69),
            ("VitaeDownBlack", 70), ("VisionUpWhite", 71), ("VisionDownBlack", 72), ("SwapHealth_Red_To_Yellow", 73),
            ("SwapHealth_Red_To_Blue", 74), ("SwapHealth_Yellow_To_Red", 75), ("SwapHealth_Yellow_To_Blue", 76),
            ("SwapHealth_Blue_To_Red", 77), ("SwapHealth_Blue_To_Yellow", 78), ("TransUpWhite", 79),
            ("TransDownBlack", 80), ("Fizzle", 81), ("PortalEntry", 82), ("PortalExit", 83), ("BreatheFlame", 84),
            ("BreatheFrost", 85), ("BreatheAcid", 86), ("BreatheLightning", 87), ("Create", 88), ("Destroy", 89),
            ("ProjectileCollision", 90), ("SplatterLowLeftBack", 91), ("SplatterLowLeftFront", 92),
            ("SplatterLowRightBack", 93), ("SplatterLowRightFront", 94), ("SplatterMidLeftBack", 95),
            ("SplatterMidLeftFront", 96), ("SplatterMidRightBack", 97), ("SplatterMidRightFront", 98),
            ("SplatterUpLeftBack", 99), ("SplatterUpLeftFront", 100), ("SplatterUpRightBack", 101),
            ("SplatterUpRightFront", 102), ("SparkLowLeftBack", 103), ("SparkLowLeftFront", 104),
            ("SparkLowRightBack", 105), ("SparkLowRightFront", 106), ("SparkMidLeftBack", 107),
            ("SparkMidLeftFront", 108), ("SparkMidRightBack", 109), ("SparkMidRightFront", 110),
            ("SparkUpLeftBack", 111), ("SparkUpLeftFront", 112), ("SparkUpRightBack", 113),
            ("SparkUpRightFront", 114), ("PortalStorm", 115), ("Hide", 116), ("UnHide", 117), ("Hidden", 118),
            ("DisappearDestroy", 119), ("SpecialState1", 120), ("SpecialState2", 121), ("SpecialState3", 122),
            ("SpecialState4", 123), ("SpecialState5", 124), ("SpecialState6", 125), ("SpecialState7", 126),
            ("SpecialState8", 127), ("SpecialState9", 128), ("SpecialState0", 129), ("SpecialStateRed", 130),
            ("SpecialStateOrange", 131), ("SpecialStateYellow", 132), ("SpecialStateGreen", 133),
            ("SpecialStateBlue", 134), ("SpecialStatePurple", 135), ("SpecialStateWhite", 136),
            ("SpecialStateBlack", 137), ("LevelUp", 138), ("EnchantUpGrey", 139), ("EnchantDownGrey", 140),
            ("WeddingBliss", 141), ("EnchantUpWhite", 142), ("EnchantDownWhite", 143), ("CampingMastery", 144),
            ("CampingIneptitude", 145), ("DispelLife", 146), ("DispelCreature", 147), ("DispelAll", 148),
            ("BunnySmite", 149), ("BaelZharonSmite", 150), ("WeddingSteele", 151), ("RestrictionEffectBlue", 152),
            ("RestrictionEffectGreen", 153), ("RestrictionEffectGold", 154), ("LayingofHands", 155),
            ("AugmentationUseAttribute", 156), ("AugmentationUseSkill", 157), ("AugmentationUseResistances", 158),
            ("AugmentationUseOther", 159), ("BlackMadness", 160), ("AetheriaLevelUp", 161),
            ("AetheriaSurgeDestruction", 162), ("AetheriaSurgeProtection", 163), ("AetheriaSurgeRegeneration", 164),
            ("AetheriaSurgeAffliction", 165), ("AetheriaSurgeFestering", 166), ("HealthDownVoid", 167),
            ("RegenDownVoid", 168), ("SkillDownVoid", 169), ("DirtyFightingHealDebuff", 170),
            ("DirtyFightingAttackDebuff", 171), ("DirtyFightingDefenseDebuff", 172),
            ("DirtyFightingDamageOverTime", 173),
        }),
        ("RadarBehavior", false, new (string, long)[]
        {
            ("Undefined", 0), ("ShowNever", 1), ("ShowMovement", 2), ("ShowAttacking", 3), ("ShowAlways", 4),
        }),
        ("RadarColor", false, new (string, long)[]
        {
            ("Default", 0), ("Blue", 1), ("Gold", 2), ("White", 3), ("Purple", 4), ("Red", 5), ("Pink", 6),
            ("Green", 7), ("Yellow", 8), ("Cyan", 9), ("BrightGreen", 16), ("Admin", 9), ("Advocate", 6),
            ("Creature", 2), ("LifeStone", 1), ("NPC", 8), ("PlayerKiller", 5), ("Portal", 4), ("Sentinel", 9),
            ("Vendor", 8), ("Fellowship", 16), ("FellowshipLeader", 16), ("PKLite", 6),
        }),
        ("SkillTrainingType", false, new (string, long)[]
        {
            ("Unusable", 0), ("Untrained", 1), ("Trained", 2), ("Specialized", 3),
        }),
        ("SpellCategory", false, new (string, long)[]
        {
            ("Undef", 0), ("StrengthRaising", 1), ("StrengthLowering", 2), ("EnduranceRaising", 3),
            ("EnduranceLowering", 4), ("QuicknessRaising", 5), ("QuicknessLowering", 6), ("CoordinationRaising", 7),
            ("CoordinationLowering", 8), ("FocusRaising", 9), ("FocusLowering", 10), ("SelfRaising", 11),
            ("SelfLowering", 12), ("FocusConcentration", 13), ("FocusDisruption", 14), ("FocusBrilliance", 15),
            ("FocusDullness", 16), ("AxeRaising", 17), ("AxeLowering", 18), ("BowRaising", 19), ("BowLowering", 20),
            ("CrossbowRaising", 21), ("CrossbowLowering", 22), ("DaggerRaising", 23), ("DaggerLowering", 24),
            ("MaceRaising", 25), ("MaceLowering", 26), ("SpearRaising", 27), ("SpearLowering", 28),
            ("StaffRaising", 29), ("StaffLowering", 30), ("SwordRaising", 31), ("SwordLowering", 32),
            ("ThrownWeaponsRaising", 33), ("ThrownWeaponsLowering", 34), ("UnarmedCombatRaising", 35),
            ("UnarmedCombatLowering", 36), ("MeleeDefenseRaising", 37), ("MeleeDefenseLowering", 38),
            ("MissileDefenseRaising", 39), ("MissileDefenseLowering", 40), ("MagicDefenseRaising", 41),
            ("MagicDefenseLowering", 42), ("CreatureEnchantmentRaising", 43), ("CreatureEnchantmentLowering", 44),
            ("ItemEnchantmentRaising", 45), ("ItemEnchantmentLowering", 46), ("LifeMagicRaising", 47),
            ("LifeMagicLowering", 48), ("WarMagicRaising", 49), ("WarMagicLowering", 50),
            ("ManaConversionRaising", 51), ("ManaConversionLowering", 52), ("ArcaneLoreRaising", 53),
            ("ArcaneLoreLowering", 54), ("AppraiseArmorRaising", 55), ("AppraiseArmorLowering", 56),
            ("AppraiseItemRaising", 57), ("AppraiseItemLowering", 58), ("AppraiseMagicItemRaising", 59),
            ("AppraiseMagicItemLowering", 60), ("AppraiseWeaponRaising", 61), ("AppraiseWeaponLowering", 62),
            ("AssessMonsterRaising", 63), ("AssessMonsterLowering", 64), ("DeceptionRaising", 65),
            ("DeceptionLowering", 66), ("HealingRaising", 67), ("HealingLowering", 68), ("JumpRaising", 69),
            ("JumpLowering", 70), ("LeadershipRaising", 71), ("LeadershipLowering", 72), ("LockpickRaising", 73),
            ("LockpickLowering", 74), ("LoyaltyRaising", 75), ("LoyaltyLowering", 76), ("RunRaising", 77),
            ("RunLowering", 78), ("HealthRaising", 79), ("HealthLowering", 80), ("StaminaRaising", 81),
            ("StaminaLowering", 82), ("ManaRaising", 83), ("ManaLowering", 84), ("ManaRemedy", 85),
            ("ManaMalediction", 86), ("HealthTransfertocaster", 87), ("HealthTransferfromcaster", 88),
            ("StaminaTransfertocaster", 89), ("StaminaTransferfromcaster", 90), ("ManaTransfertocaster", 91),
            ("ManaTransferfromcaster", 92), ("HealthAccelerating", 93), ("HealthDecelerating", 94),
            ("StaminaAccelerating", 95), ("StaminaDecelerating", 96), ("ManaAccelerating", 97),
            ("ManaDecelerating", 98), ("VitaeRaising", 99), ("VitaeLowering", 100), ("AcidProtection", 101),
            ("AcidVulnerability", 102), ("BludgeonProtection", 103), ("BludgeonVulnerability", 104),
            ("ColdProtection", 105), ("ColdVulnerability", 106), ("ElectricProtection", 107),
            ("ElectricVulnerability", 108), ("FireProtection", 109), ("FireVulnerability", 110),
            ("PierceProtection", 111), ("PierceVulnerability", 112), ("SlashProtection", 113),
            ("SlashVulnerability", 114), ("ArmorRaising", 115), ("ArmorLowering", 116), ("AcidMissile", 117),
            ("BludgeoningMissile", 118), ("ColdMissile", 119), ("ElectricMissile", 120), ("FireMissile", 121),
            ("PiercingMissile", 122), ("SlashingMissile", 123), ("AcidSeeker", 124), ("BludgeoningSeeker", 125),
            ("ColdSeeker", 126), ("ElectricSeeker", 127), ("FireSeeker", 128), ("PiercingSeeker", 129),
            ("SlashingSeeker", 130), ("AcidBurst", 131), ("BludgeoningBurst", 132), ("ColdBurst", 133),
            ("ElectricBurst", 134), ("FireBurst", 135), ("PiercingBurst", 136), ("SlashingBurst", 137),
            ("AcidBlast", 138), ("BludgeoningBlast", 139), ("ColdBlast", 140), ("ElectricBlast", 141),
            ("FireBlast", 142), ("PiercingBlast", 143), ("SlashingBlast", 144), ("AcidScatter", 145),
            ("BludgeoningScatter", 146), ("ColdScatter", 147), ("ElectricScatter", 148), ("FireScatter", 149),
            ("PiercingScatter", 150), ("SlashingScatter", 151), ("AttackModRaising", 152),
            ("AttackModLowering", 153), ("DamageRaising", 154), ("DamageLowering", 155), ("DefenseModRaising", 156),
            ("DefenseModLowering", 157), ("WeaponTimeRaising", 158), ("WeaponTimeLowering", 159),
            ("ArmorValueRaising", 160), ("ArmorValueLowering", 161), ("AcidResistanceRaising", 162),
            ("AcidResistanceLowering", 163), ("BludgeonResistanceRaising", 164), ("BludgeonResistanceLowering", 165),
            ("ColdResistanceRaising", 166), ("ColdResistanceLowering", 167), ("ElectricResistanceRaising", 168),
            ("ElectricResistanceLowering", 169), ("FireResistanceRaising", 170), ("FireResistanceLowering", 171),
            ("PierceResistanceRaising", 172), ("PierceResistanceLowering", 173), ("SlashResistanceRaising", 174),
            ("SlashResistanceLowering", 175), ("BludgeoningResistanceRaising", 176),
            ("BludgeoningResistanceLowering", 177), ("SlashingResistanceRaising", 178),
            ("SlashingResistanceLowering", 179), ("PiercingResistanceRaising", 180),
            ("PiercingResistanceLowering", 181), ("ElectricalResistanceRaising", 182),
            ("ElectricalResistanceLowering", 183), ("FrostResistanceRaising", 184), ("FrostResistanceLowering", 185),
            ("FlameResistanceRaising", 186), ("FlameResistanceLowering", 187), ("AcidicResistanceRaising", 188),
            ("AcidicResistanceLowering", 189), ("ArmorLevelRaising", 190), ("ArmorLevelLowering", 191),
            ("LockpickResistanceRaising", 192), ("LockpickResistanceLowering", 193),
            ("ManaConversionModLowering", 194), ("ManaConversionModRaising", 195), ("VisionRaising", 196),
            ("VisionLowering", 197), ("TransparencyRaising", 198), ("TransparencyLowering", 199), ("PortalTie", 200),
            ("PortalRecall", 201), ("PortalCreation", 202), ("PortalItemCreation", 203), ("Vitae", 204),
            ("AssessPersonRaising", 205), ("AssessPersonLowering", 206), ("AcidVolley", 207),
            ("BludgeoningVolley", 208), ("FrostVolley", 209), ("LightningVolley", 210), ("FlameVolley", 211),
            ("ForceVolley", 212), ("BladeVolley", 213), ("PortalSending", 214), ("LifestoneSending", 215),
            ("CookingRaising", 216), ("CookingLowering", 217), ("FletchingRaising", 218), ("FletchingLowering", 219),
            ("AlchemyLowering", 220), ("AlchemyRaising", 221), ("AcidRing", 222), ("BludgeoningRing", 223),
            ("ColdRing", 224), ("ElectricRing", 225), ("FireRing", 226), ("PiercingRing", 227),
            ("SlashingRing", 228), ("AcidWall", 229), ("BludgeoningWall", 230), ("ColdWall", 231),
            ("ElectricWall", 232), ("FireWall", 233), ("PiercingWall", 234), ("SlashingWall", 235),
            ("AcidStrike", 236), ("BludgeoningStrike", 237), ("ColdStrike", 238), ("ElectricStrike", 239),
            ("FireStrike", 240), ("PiercingStrike", 241), ("SlashingStrike", 242), ("AcidStreak", 243),
            ("BludgeoningStreak", 244), ("ColdStreak", 245), ("ElectricStreak", 246), ("FireStreak", 247),
            ("PiercingStreak", 248), ("SlashingStreak", 249), ("Dispel", 250), ("CreatureMysticRaising", 251),
            ("CreatureMysticLowering", 252), ("ItemMysticRaising", 253), ("ItemMysticLowering", 254),
            ("WarMysticRaising", 255), ("WarMysticLowering", 256), ("HealthRestoring", 257),
            ("HealthDepleting", 258), ("ManaRestoring", 259), ("ManaDepleting", 260), ("StrengthIncrease", 261),
            ("StrengthDecrease", 262), ("EnduranceIncrease", 263), ("EnduranceDecrease", 264),
            ("QuicknessIncrease", 265), ("QuicknessDecrease", 266), ("CoordinationIncrease", 267),
            ("CoordinationDecrease", 268), ("FocusIncrease", 269), ("FocusDecrease", 270), ("SelfIncrease", 271),
            ("SelfDecrease", 272), ("GreatVitalityRaising", 273), ("PoorVitalityLowering", 274),
            ("GreatVigorRaising", 275), ("PoorVigorLowering", 276), ("GreaterIntellectRaising", 277),
            ("LessorIntellectLowering", 278), ("LifeGiverRaising", 279), ("LifeTakerLowering", 280),
            ("StaminaGiverRaising", 281), ("StaminaTakerLowering", 282), ("ManaGiverRaising", 283),
            ("ManaTakerLowering", 284), ("AcidWardProtection", 285), ("AcidWardVulnerability", 286),
            ("FireWardProtection", 287), ("FireWardVulnerability", 288), ("ColdWardProtection", 289),
            ("ColdWardVulnerability", 290), ("ElectricWardProtection", 291), ("ElectricWardVulnerability", 292),
            ("LeadershipObedienceRaising", 293), ("LeadershipObedienceLowering", 294),
            ("MeleeDefenseShelterRaising", 295), ("MeleeDefenseShelterLowering", 296),
            ("MissileDefenseShelterRaising", 297), ("MissileDefenseShelterLowering", 298),
            ("MagicDefenseShelterRaising", 299), ("MagicDefenseShelterLowering", 300), ("HuntersAcumenRaising", 301),
            ("HuntersAcumenLowering", 302), ("StillWaterRaising", 303), ("StillWaterLowering", 304),
            ("StrengthofEarthRaising", 305), ("StrengthofEarthLowering", 306), ("TorrentRaising", 307),
            ("TorrentLowering", 308), ("GrowthRaising", 309), ("GrowthLowering", 310), ("CascadeAxeRaising", 311),
            ("CascadeAxeLowering", 312), ("CascadeDaggerRaising", 313), ("CascadeDaggerLowering", 314),
            ("CascadeMaceRaising", 315), ("CascadeMaceLowering", 316), ("CascadeSpearRaising", 317),
            ("CascadeSpearLowering", 318), ("CascadeStaffRaising", 319), ("CascadeStaffLowering", 320),
            ("StoneCliffsRaising", 321), ("StoneCliffsLowering", 322), ("MaxDamageRaising", 323),
            ("MaxDamageLowering", 324), ("BowDamageRaising", 325), ("BowDamageLowering", 326),
            ("BowRangeRaising", 327), ("BowRangeLowering", 328), ("ExtraDefenseModRaising", 329),
            ("ExtraDefenseModLowering", 330), ("ExtraBowSkillRaising", 331), ("ExtraBowSkillLowering", 332),
            ("ExtraAlchemySkillRaising", 333), ("ExtraAlchemySkillLowering", 334),
            ("ExtraArcaneLoreSkillRaising", 335), ("ExtraArcaneLoreSkillLowering", 336),
            ("ExtraAppraiseArmorSkillRaising", 337), ("ExtraAppraiseArmorSkillLowering", 338),
            ("ExtraCookingSkillRaising", 339), ("ExtraCookingSkillLowering", 340),
            ("ExtraCrossbowSkillRaising", 341), ("ExtraCrossbowSkillLowering", 342),
            ("ExtraDeceptionSkillRaising", 343), ("ExtraDeceptionSkillLowering", 344),
            ("ExtraLoyaltySkillRaising", 345), ("ExtraLoyaltySkillLowering", 346),
            ("ExtraFletchingSkillRaising", 347), ("ExtraFletchingSkillLowering", 348),
            ("ExtraHealingSkillRaising", 349), ("ExtraHealingSkillLowering", 350),
            ("ExtraMeleeDefenseSkillRaising", 351), ("ExtraMeleeDefenseSkillLowering", 352),
            ("ExtraAppraiseItemSkillRaising", 353), ("ExtraAppraiseItemSkillLowering", 354),
            ("ExtraJumpingSkillRaising", 355), ("ExtraJumpingSkillLowering", 356),
            ("ExtraLifeMagicSkillRaising", 357), ("ExtraLifeMagicSkillLowering", 358),
            ("ExtraLockpickSkillRaising", 359), ("ExtraLockpickSkillLowering", 360),
            ("ExtraAppraiseMagicItemSkillRaising", 361), ("ExtraAppraiseMagicItemSkillLowering", 362),
            ("ExtraManaConversionSkillRaising", 363), ("ExtraManaConversionSkillLowering", 364),
            ("ExtraAssessCreatureSkillRaising", 365), ("ExtraAssessCreatureSkillLowering", 366),
            ("ExtraAssessPersonSkillRaising", 367), ("ExtraAssessPersonSkillLowering", 368),
            ("ExtraRunSkillRaising", 369), ("ExtraRunSkillLowering", 370), ("ExtraSwordSkillRaising", 371),
            ("ExtraSwordSkillLowering", 372), ("ExtraThrownWeaponsSkillRaising", 373),
            ("ExtraThrownWeaponsSkillLowering", 374), ("ExtraUnarmedCombatSkillRaising", 375),
            ("ExtraUnarmedCombatSkillLowering", 376), ("ExtraAppraiseWeaponSkillRaising", 377),
            ("ExtraAppraiseWeaponSkillLowering", 378), ("ArmorIncrease", 379), ("ArmorDecrease", 380),
            ("ExtraAcidResistanceRaising", 381), ("ExtraAcidResistanceLowering", 382),
            ("ExtraBludgeonResistanceRaising", 383), ("ExtraBludgeonResistanceLowering", 384),
            ("ExtraFireResistanceRaising", 385), ("ExtraFireResistanceLowering", 386),
            ("ExtraColdResistanceRaising", 387), ("ExtraColdResistanceLowering", 388),
            ("ExtraAttackModRaising", 389), ("ExtraAttackModLowering", 390), ("ExtraArmorValueRaising", 391),
            ("ExtraArmorValueLowering", 392), ("ExtraPierceResistanceRaising", 393),
            ("ExtraPierceResistanceLowering", 394), ("ExtraSlashResistanceRaising", 395),
            ("ExtraSlashResistanceLowering", 396), ("ExtraElectricResistanceRaising", 397),
            ("ExtraElectricResistanceLowering", 398), ("ExtraWeaponTimeRaising", 399),
            ("ExtraWeaponTimeLowering", 400), ("BludgeonWardProtection", 401), ("BludgeonWardVulnerability", 402),
            ("SlashWardProtection", 403), ("SlashWardVulnerability", 404), ("PierceWardProtection", 405),
            ("PierceWardVulnerability", 406), ("StaminaRestoring", 407), ("StaminaDepleting", 408),
            ("Fireworks", 409), ("HealthDivide", 410), ("StaminaDivide", 411), ("ManaDivide", 412),
            ("CoordinationIncrease2", 413), ("StrengthIncrease2", 414), ("FocusIncrease2", 415),
            ("EnduranceIncrease2", 416), ("SelfIncrease2", 417), ("MeleeDefenseMultiply", 418),
            ("MissileDefenseMultiply", 419), ("MagicDefenseMultiply", 420), ("AttributesDecrease", 421),
            ("LifeGiverRaising2", 422), ("ItemEnchantmentRaising2", 423), ("SkillsDecrease", 424),
            ("ExtraManaConversionBonus", 425), ("WarMysticRaising2", 426), ("WarMysticLowering2", 427),
            ("MagicDefenseShelterRaising2", 428), ("ExtraLifeMagicSkillRaising2", 429),
            ("CreatureMysticRaising2", 430), ("ItemMysticRaising2", 431), ("ManaRaising2", 432),
            ("SelfRaising2", 433), ("CreatureEnchantmentRaising2", 434), ("SalvagingRaising", 435),
            ("ExtraSalvagingRaising", 436), ("ExtraSalvagingRaising2", 437), ("CascadeAxeRaising2", 438),
            ("ExtraBowSkillRaising2", 439), ("ExtraThrownWeaponsSkillRaising2", 440),
            ("ExtraCrossbowSkillRaising2", 441), ("CascadeDaggerRaising2", 442), ("CascadeMaceRaising2", 443),
            ("ExtraUnarmedCombatSkillRaising2", 444), ("CascadeSpearRaising2", 445), ("CascadeStaffRaising2", 446),
            ("ExtraSwordSkillRaising2", 447), ("AcidProtectionRare", 448), ("AcidResistanceRaisingRare", 449),
            ("AlchemyRaisingRare", 450), ("AppraisalResistanceLoweringRare", 451), ("AppraiseArmorRaisingRare", 452),
            ("AppraiseItemRaisingRare", 453), ("AppraiseMagicItemRaisingRare", 454),
            ("AppraiseWeaponRaisingRare", 455), ("ArcaneLoreRaisingRare", 456), ("ArmorRaisingRare", 457),
            ("ArmorValueRaisingRare", 458), ("AssessMonsterRaisingRare", 459), ("AssessPersonRaisingRare", 460),
            ("AttackModRaisingRare", 461), ("AxeRaisingRare", 462), ("BludgeonProtectionRare", 463),
            ("BludgeonResistanceRaisingRare", 464), ("BowRaisingRare", 465), ("ColdProtectionRare", 466),
            ("ColdResistanceRaisingRare", 467), ("CookingRaisingRare", 468), ("CoordinationRaisingRare", 469),
            ("CreatureEnchantmentRaisingRare", 470), ("CrossbowRaisingRare", 471), ("DaggerRaisingRare", 472),
            ("DamageRaisingRare", 473), ("DeceptionRaisingRare", 474), ("DefenseModRaisingRare", 475),
            ("ElectricProtectionRare", 476), ("ElectricResistanceRaisingRare", 477), ("EnduranceRaisingRare", 478),
            ("FireProtectionRare", 479), ("FireResistanceRaisingRare", 480), ("FletchingRaisingRare", 481),
            ("FocusRaisingRare", 482), ("HealingRaisingRare", 483), ("HealthAcceleratingRare", 484),
            ("ItemEnchantmentRaisingRare", 485), ("JumpRaisingRare", 486), ("LeadershipRaisingRare", 487),
            ("LifeMagicRaisingRare", 488), ("LockpickRaisingRare", 489), ("LoyaltyRaisingRare", 490),
            ("MaceRaisingRare", 491), ("MagicDefenseRaisingRare", 492), ("ManaAcceleratingRare", 493),
            ("ManaConversionRaisingRare", 494), ("MeleeDefenseRaisingRare", 495), ("MissileDefenseRaisingRare", 496),
            ("PierceProtectionRare", 497), ("PierceResistanceRaisingRare", 498), ("QuicknessRaisingRare", 499),
            ("RunRaisingRare", 500), ("SelfRaisingRare", 501), ("SlashProtectionRare", 502),
            ("SlashResistanceRaisingRare", 503), ("SpearRaisingRare", 504), ("StaffRaisingRare", 505),
            ("StaminaAcceleratingRare", 506), ("StrengthRaisingRare", 507), ("SwordRaisingRare", 508),
            ("ThrownWeaponsRaisingRare", 509), ("UnarmedCombatRaisingRare", 510), ("WarMagicRaisingRare", 511),
            ("WeaponTimeRaisingRare", 512), ("ArmorIncreaseInkyArmor", 513), ("MagicDefenseShelterRaisingFiun", 514),
            ("ExtraRunSkillRaisingFiun", 515), ("ExtraManaConversionSkillRaisingFiun", 516),
            ("AttributesIncreaseCantrip1", 517), ("ExtraMeleeDefenseSkillRaising2", 518),
            ("ACTDPurchaseRewardSpell", 519), ("ACTDPurchaseRewardSpellHealth", 520),
            ("SaltAshAttackModRaising", 521), ("QuicknessIncrease2", 522), ("ExtraAlchemySkillRaising2", 523),
            ("ExtraCookingSkillRaising2", 524), ("ExtraFletchingSkillRaising2", 525),
            ("ExtraLockpickSkillRaising2", 526), ("MucorManaWell", 527), ("StaminaRestoring2", 528),
            ("AllegianceRaising", 529), ("HealthDoT", 530), ("HealthDoTSecondary", 531), ("HealthDoTTertiary", 532),
            ("HealthHoT", 533), ("HealthHoTSecondary", 534), ("HealthHoTTertiary", 535),
            ("HealthDivideSecondary", 536), ("HealthDivideTertiary", 537), ("SetSwordRaising", 538),
            ("SetAxeRaising", 539), ("SetDaggerRaising", 540), ("SetMaceRaising", 541), ("SetSpearRaising", 542),
            ("SetStaffRaising", 543), ("SetUnarmedRaising", 544), ("SetBowRaising", 545),
            ("SetCrossbowRaising", 546), ("SetThrownRaising", 547), ("SetItemEnchantmentRaising", 548),
            ("SetCreatureEnchantmentRaising", 549), ("SetWarMagicRaising", 550), ("SetLifeMagicRaising", 551),
            ("SetMeleeDefenseRaising", 552), ("SetMissileDefenseRaising", 553), ("SetMagicDefenseRaising", 554),
            ("SetStaminaAccelerating", 555), ("SetCookingRaising", 556), ("SetFletchingRaising", 557),
            ("SetLockpickRaising", 558), ("SetAlchemyRaising", 559), ("SetSalvagingRaising", 560),
            ("SetArmorExpertiseRaising", 561), ("SetWeaponExpertiseRaising", 562), ("SetItemTinkeringRaising", 563),
            ("SetMagicItemExpertiseRaising", 564), ("SetLoyaltyRaising", 565), ("SetStrengthRaising", 566),
            ("SetEnduranceRaising", 567), ("SetCoordinationRaising", 568), ("SetQuicknessRaising", 569),
            ("SetFocusRaising", 570), ("SetWillpowerRaising", 571), ("SetHealthRaising", 572),
            ("SetStaminaRaising", 573), ("SetManaRaising", 574), ("SetSprintRaising", 575),
            ("SetJumpingRaising", 576), ("SetSlashResistanceRaising", 577), ("SetBludgeonResistanceRaising", 578),
            ("SetPierceResistanceRaising", 579), ("SetFlameResistanceRaising", 580),
            ("SetAcidResistanceRaising", 581), ("SetFrostResistanceRaising", 582),
            ("SetLightningResistanceRaising", 583), ("CraftingLockPickRaising", 584),
            ("CraftingFletchingRaising", 585), ("CraftingCookingRaising", 586), ("CraftingAlchemyRaising", 587),
            ("CraftingArmorTinkeringRaising", 588), ("CraftingWeaponTinkeringRaising", 589),
            ("CraftingMagicTinkeringRaising", 590), ("CraftingItemTinkeringRaising", 591),
            ("SkillPercentAlchemyRaising", 592), ("TwoHandedRaising", 593), ("TwoHandedLowering", 594),
            ("ExtraTwoHandedSkillRaising", 595), ("ExtraTwoHandedSkillLowering", 596),
            ("ExtraTwoHandedSkillRaising2", 597), ("TwoHandedRaisingRare", 598), ("SetTwoHandedRaising", 599),
            ("GearCraftRaising", 600), ("GearCraftLowering", 601), ("ExtraGearCraftSkillRaising", 602),
            ("ExtraGearCraftSkillLowering", 603), ("ExtraGearCraftSkillRaising2", 604),
            ("GearCraftRaisingRare", 605), ("SetGearCraftRaising", 606), ("LoyaltyManaRaising", 607),
            ("LoyaltyStaminaRaising", 608), ("LeadershipHealthRaising", 609), ("TrinketDamageRaising", 610),
            ("TrinketDamageLowering", 611), ("TrinketHealthRaising", 612), ("TrinketStaminaRaising", 613),
            ("TrinketManaRaising", 614), ("TrinketXPRaising", 615), ("DeceptionArcaneLoreRaising", 616),
            ("HealOverTimeRaising", 617), ("DamageOverTimeRaising", 618), ("HealingResistRatingRaising", 619),
            ("AetheriaDamageRatingRaising", 620), ("AetheriaDamageReductionRaising", 621),
            ("AetheriaHealthRaising", 623), ("AetheriaStaminaRaising", 624), ("AetheriaManaRaising", 625),
            ("AetheriaCriticalDamageRaising", 626), ("AetheriaHealingAmplificationRaising", 627),
            ("AetheriaProcDamageRatingRaising", 628), ("AetheriaProcDamageReductionRaising", 629),
            ("AetheriaProcHealthOverTimeRaising", 630), ("AetheriaProcDamageOverTimeRaising", 631),
            ("AetheriaProcHealingReductionRaising", 632), ("RareDamageRatingRaising", 633),
            ("RareDamageReductionRatingRaising", 634), ("AetheriaEnduranceRaising", 635),
            ("NetherDamageOverTimeRaising", 636), ("NetherDamageOverTimeRaising2", 637),
            ("NetherDamageOverTimeRaising3", 638), ("NetherStreak", 639), ("NetherMissile", 640),
            ("NetherRing", 641), ("NetherDamageRatingLowering", 642), ("NetherDamageHealingReductionRaising", 643),
            ("VoidMagicLowering", 644), ("VoidMagicRaising", 645), ("VoidMysticRaising", 646),
            ("SetVoidMagicRaising", 647), ("VoidMagicRaisingRare", 648), ("VoidMysticRaising2", 649),
            ("LuminanceDamageRatingRaising", 650), ("LuminanceDamageReductionRaising", 651),
            ("LuminanceHealthRaising", 652), ("AetheriaCriticalReductionRaising", 653),
            ("ExtraMissileDefenseSkillRaising", 654), ("ExtraMissileDefenseSkillLowering", 655),
            ("ExtraMissileDefenseSkillRaising2", 656), ("AetheriaHealthResistanceRaising", 657),
            ("AetheriaDotResistanceRaising", 658), ("CloakSkillRaising", 659), ("CloakAllSkillRaising", 660),
            ("CloakMagicDefenseLowering", 661), ("CloakMeleeDefenseLowering", 662),
            ("CloakMissileDefenseLowering", 663), ("DirtyFightingLowering", 664), ("DirtyFightingRaising", 665),
            ("ExtraDirtyFightingRaising", 666), ("DualWieldLowering", 667), ("DualWieldRaising", 668),
            ("ExtraDualWieldRaising", 669), ("RecklessnessLowering", 670), ("RecklessnessRaising", 671),
            ("ExtraRecklessnessRaising", 672), ("ShieldLowering", 673), ("ShieldRaising", 674),
            ("ExtraShieldRaising", 675), ("SneakAttackLowering", 676), ("SneakAttackRaising", 677),
            ("ExtraSneakAttackRaising", 678), ("RareDirtyFightingRaising", 679), ("RareDualWieldRaising", 680),
            ("RareRecklessnessRaising", 681), ("RareShieldRaising", 682), ("RareSneakAttackRaising", 683),
            ("DFAttackSkillDebuff", 684), ("DFBleedDamage", 685), ("DFDefenseSkillDebuff", 686),
            ("DFHealingDebuff", 687), ("SetDirtyFightingRaising", 688), ("SetDualWieldRaising", 689),
            ("SetRecklessnessRaising", 690), ("SetShieldRaising", 691), ("SetSneakAttackRaising", 692),
            ("LifeGiverMhoire", 693), ("RareDamageRatingRaising2", 694), ("SpellDamageRaising", 695),
            ("SummoningRaising", 696), ("SummoningLowering", 697), ("ExtraSummoningSkillRaising", 698),
            ("SetSummoningRaising", 699), ("ParagonEnduranceRaising", 704), ("ParagonManaRaising", 705),
            ("ParagonStaminaRaising", 706), ("ParagonDirtyFightingRaising", 707), ("ParagonDualWieldRaising", 708),
            ("ParagonRecklessnessRaising", 709), ("ParagonSneakAttackRaising", 710),
            ("ParagonDamageRatingRaising", 711), ("ParagonDamageReductionRatingRaising", 712),
            ("ParagonCriticalDamageRatingRaising", 713), ("ParagonCriticalDamageReductionRatingRaising", 714),
            ("ParagonAxeRaising", 715), ("ParagonDaggerRaising", 716), ("ParagonSwordRaising", 717),
            ("ParagonWarMagicRaising", 718), ("ParagonLifeMagicRaising", 719), ("ParagonVoidMagicRaising", 720),
            ("ParagonBowRaising", 721), ("ParagonStrengthRaising", 722), ("ParagonCoordinationRaising", 723),
            ("ParagonQuicknessRaising", 724), ("ParagonFocusRaising", 725), ("ParagonWillpowerRaising", 726),
            ("ParagonTwoHandedRaising", 727), ("GauntletDamageReductionRatingRaising", 728),
            ("GauntletDamageRatingRaising", 729), ("GauntletHealingRatingRaising", 730),
            ("GauntletVitalityRaising", 731), ("GauntletCriticalDamageRatingRaising", 732),
            ("GauntletCriticalDamageReductionRatingRaising", 733),
        }),
        ("SpellFlags", true, new (string, long)[]
        {
            ("Resistable", 1), ("PKSensitive", 2), ("Beneficial", 4), ("SelfTargeted", 8), ("Reversed", 16),
            ("NotIndoor", 32), ("NotOutdoor", 64), ("NotResearchable", 128), ("Projectile", 256),
            ("CreatureSpell", 512), ("ExcludedFromItemDescriptions", 1024), ("IgnoresManaConversion", 2048),
            ("NonTrackingProjectile", 4096), ("FellowshipSpell", 8192), ("FastCast", 16384),
            ("IndoorLongRange", 32768), ("DamageOverTime", 65536), ("UNKNOWN", 131072),
        }),
        ("SpellType", false, new (string, long)[]
        {
            ("Undef", 0), ("Enchantment", 1), ("Projectile", 2), ("Boost", 3), ("Transfer", 4), ("PortalLink", 5),
            ("PortalRecall", 6), ("PortalSummon", 7), ("PortalSending", 8), ("Dispel", 9), ("LifeProjectile", 10),
            ("FellowBoost", 11), ("FellowEnchantment", 12), ("FellowPortalSending", 13), ("FellowDispel", 14),
            ("EnchantmentProjectile", 15),
        }),
        ("TradeSide", false, new (string, long)[]
        {
            ("Self", 1), ("Partner", 2),
        }),
        ("UsableType", true, new (string, long)[]
        {
            ("SourceUnusable", 1), ("SourceSelf", 2), ("SourceWielded", 4), ("SourceContained", 8),
            ("SourceViewed", 16), ("SourceRemote", 32), ("SourceNoApproach", 64), ("SourceObjectSelf", 128),
            ("TargetUnusable", 65536), ("TargetSelf", 131072), ("TargetWielded", 262144),
            ("TargetContained", 524288), ("TargetViewed", 1048576), ("TargetRemote", 2097152),
            ("TargetNoApproach", 4194304), ("TargetObjectSelf", 8388608),
        }),
        ("Vital", false, new (string, long)[]
        {
            ("Undef", 0), ("MaxHealth", 1), ("Health", 2), ("MaxStamina", 3), ("Stamina", 4), ("MaxMana", 5),
            ("Mana", 6),
        }),
        ("WeenieError", false, new (string, long)[]
        {
            ("None", 0), ("NoMem", 1), ("BadParam", 2), ("DivZero", 3), ("SegV", 4), ("Unimplemented", 5),
            ("UnknownMessageType", 6), ("NoAnimationTable", 7), ("NoPhysicsObject", 8), ("NoBookieObject", 9),
            ("NoWslObject", 10), ("NoMotionInterpreter", 11), ("UnhandledSwitch", 12),
            ("DefaultConstructorCalled", 13), ("InvalidCombatManeuver", 14), ("BadCast", 15), ("MissingQuality", 16),
            ("MissingDatabaseObject", 18), ("NoCallbackSet", 19), ("CorruptQuality", 20), ("BadContext", 21),
            ("NoEphseqManager", 22), ("BadMovementEvent", 23), ("CannotCreateNewObject", 24),
            ("NoControllerObject", 25), ("CannotSendEvent", 26), ("PhysicsCantTransition", 27),
            ("PhysicsMaxDistanceExceeded", 28), ("YoureTooBusy", 29), ("CannotSendMessage", 31),
            ("IllegalInventoryTransaction", 32), ("ExternalWeenieObject", 33), ("InternalWeenieObject", 34),
            ("MotionFailure", 35), ("YouCantJumpWhileInTheAir", 36), ("InqCylSphereFailure", 37),
            ("ThatIsNotAValidCommand", 38), ("CarryingItem", 39), ("Frozen", 40), ("Stuck", 41),
            ("YouAreTooEncumbered", 42), ("BadContain", 44), ("BadParent", 45), ("BadDrop", 46), ("BadRelease", 47),
            ("MsgBadMsg", 48), ("MsgUnpackFailed", 49), ("MsgNoMsg", 50), ("MsgUnderflow", 51), ("MsgOverflow", 52),
            ("MsgCallbackFailed", 53), ("ActionCancelled", 54), ("ObjectGone", 55), ("NoObject", 56),
            ("CantGetThere", 57), ("Dead", 58), ("ILeftTheWorld", 59), ("ITeleported", 60), ("YouChargedTooFar", 61),
            ("YouAreTooTiredToDoThat", 62), ("CantCrouchInCombat", 63), ("CantSitInCombat", 64),
            ("CantLieDownInCombat", 65), ("CantChatEmoteInCombat", 66), ("NoMtableData", 67),
            ("CantChatEmoteNotStanding", 68), ("TooManyActions", 69), ("Hidden", 70), ("GeneralMovementFailure", 71),
            ("YouCantJumpFromThisPosition", 72), ("CantJumpLoadedDown", 73), ("YouKilledYourself", 74),
            ("MsgResponseFailure", 75), ("ObjectIsStatic", 76), ("InvalidPkStatus", 77), ("InvalidXpAmount", 1001),
            ("InvalidPpCalculation", 1002), ("InvalidCpCalculation", 1003), ("UnhandledStatAnswer", 1004),
            ("HeartAttack", 1005), ("TheContainerIsClosed", 1006), ("InvalidInventoryLocation", 1008),
            ("ChangeCombatModeFailure", 1009), ("FullInventoryLocation", 1010),
            ("ConflictingInventoryLocation", 1011), ("ItemNotPending", 1012), ("BeWieldedFailure", 1013),
            ("BeDroppedFailure", 1014), ("YouAreTooFatiguedToAttack", 1015), ("YouAreOutOfAmmunition", 1016),
            ("YourAttackMisfired", 1017), ("YouveAttemptedAnImpossibleSpellPath", 1018),
            ("MagicIncompleteAnimList", 1019), ("MagicInvalidSpellType", 1020),
            ("MagicInqPositionAndVelocityFailure", 1021), ("YouDontKnowThatSpell", 1022),
            ("IncorrectTargetType", 1023), ("YouDontHaveAllTheComponents", 1024),
            ("YouDontHaveEnoughManaToCast", 1025), ("YourSpellFizzled", 1026), ("YourSpellTargetIsMissing", 1027),
            ("YourProjectileSpellMislaunched", 1028), ("MagicSpellbookAddSpellFailure", 1029),
            ("MagicTargetOutOfRange", 1030), ("YourSpellCannotBeCastOutside", 1031),
            ("YourSpellCannotBeCastInside", 1032), ("MagicGeneralFailure", 1033),
            ("YouAreUnpreparedToCastASpell", 1034), ("YouveAlreadySwornAllegiance", 1035),
            ("CantSwearAllegianceInsufficientXp", 1036), ("AllegianceIgnoringRequests", 1037),
            ("AllegianceSquelched", 1038), ("AllegianceMaxDistanceExceeded", 1039), ("AllegianceIllegalLevel", 1040),
            ("AllegianceBadCreation", 1041), ("AllegiancePatronBusy", 1042), ("YouAreNotInAllegiance", 1044),
            ("AllegianceRemoveHierarchyFailure", 1045), ("FellowshipIgnoringRequests", 1047),
            ("FellowshipSquelched", 1048), ("FellowshipMaxDistanceExceeded", 1049), ("FellowshipMember", 1050),
            ("FellowshipIllegalLevel", 1051), ("FellowshipRecruitBusy", 1052), ("YouMustBeLeaderOfFellowship", 1053),
            ("YourFellowshipIsFull", 1054), ("FellowshipNameIsNotPermitted", 1055), ("LevelTooLow", 1056),
            ("LevelTooHigh", 1057), ("ThatChannelDoesntExist", 1058), ("YouCantUseThatChannel", 1059),
            ("YouAreAlreadyOnThatChannel", 1060), ("YouAreNotOnThatChannel", 1061), ("AttunedItem", 1062),
            ("YouCannotMergeDifferentStacks", 1063), ("YouCannotMergeEnchantedItems", 1064),
            ("YouMustControlAtLeastOneStack", 1065), ("CurrentlyAttacking", 1066), ("MissileAttackNotOk", 1067),
            ("TargetNotAcquired", 1068), ("ImpossibleShot", 1069), ("BadWeaponSkill", 1070),
            ("UnwieldFailure", 1071), ("LaunchFailure", 1072), ("ReloadFailure", 1073),
            ("UnableToMakeCraftReq", 1074), ("CraftAnimationFailed", 1075),
            ("YouCantCraftWithThatNumberOfItems", 1076), ("CraftGeneralErrorUiMsg", 1077),
            ("CraftGeneralErrorNoUiMsg", 1078), ("YouDoNotPassCraftingRequirements", 1079),
            ("YouDoNotHaveAllTheNecessaryItems", 1080), ("NotAllTheItemsAreAvailable", 1081),
            ("YouMustBeInPeaceModeToTrade", 1082), ("YouAreNotTrainedInThatTradeSkill", 1083),
            ("YourHandsMustBeFree", 1084), ("YouCannotLinkToThatPortal", 1085),
            ("YouHaveSolvedThisQuestTooRecently", 1086), ("YouHaveSolvedThisQuestTooManyTimes", 1087),
            ("QuestUnknown", 1088), ("QuestTableCorrupt", 1089), ("QuestBad", 1090), ("QuestDuplicate", 1091),
            ("QuestUnsolved", 1092), ("ItemRequiresQuestToBePickedUp", 1093), ("QuestSolvedTooLongAgo", 1094),
            ("TradeIgnoringRequests", 1100), ("TradeSquelched", 1101), ("TradeMaxDistanceExceeded", 1102),
            ("TradeAlreadyTrading", 1103), ("TradeBusy", 1104), ("TradeClosed", 1105), ("TradeExpired", 1106),
            ("TradeItemBeingTraded", 1107), ("TradeNonEmptyContainer", 1108), ("TradeNonCombatMode", 1109),
            ("TradeIncomplete", 1110), ("TradeStampMismatch", 1111), ("TradeUnopened", 1112), ("TradeEmpty", 1113),
            ("TradeAlreadyAccepted", 1114), ("TradeOutOfSync", 1115), ("PKsMayNotUsePortal", 1116),
            ("NonPKsMayNotUsePortal", 1117), ("HouseAbandoned", 1118), ("HouseEvicted", 1119),
            ("HouseAlreadyOwned", 1120), ("HouseBuyFailed", 1121), ("HouseRentFailed", 1122), ("Hooked", 1123),
            ("MagicInvalidPosition", 1125), ("YouMustHaveDarkMajestyToUsePortal", 1126), ("InvalidAmmoType", 1127),
            ("SkillTooLow", 1128), ("YouHaveUsedAllTheHooks", 1129), ("TradeAiDoesntWant", 1130),
            ("HookHouseNotOwned", 1131), ("YouMustCompleteQuestToUsePortal", 1140), ("HouseNoAllegiance", 1150),
            ("YouMustOwnHouseToUseCommand", 1151), ("YourMonarchDoesNotOwnAMansionOrVilla", 1152),
            ("YourMonarchsHouseIsNotAMansionOrVilla", 1153), ("YourMonarchHasClosedTheMansion", 1154),
            ("YouMustBeMonarchToPurchaseDwelling", 1162), ("AllegianceTimeout", 1165),
            ("YourOfferOfAllegianceWasIgnored", 1166), ("ConfirmationInProgress", 1167),
            ("YouMustBeAMonarchToUseCommand", 1168), ("YouMustSpecifyCharacterToBoot", 1169),
            ("YouCantBootYourself", 1170), ("ThatCharacterDoesNotExist", 1171),
            ("ThatPersonIsNotInYourAllegiance", 1172), ("CantBreakFromPatronNotInAllegiance", 1173),
            ("YourAllegianceHasBeenDissolved", 1174), ("YourPatronsAllegianceHasBeenBroken", 1175),
            ("YouHaveMovedTooFar", 1176), ("TeleToInvalidPosition", 1177), ("MustHaveDarkMajestyToUse", 1178),
            ("YouFailToLinkWithLifestone", 1179), ("YouWanderedTooFarToLinkWithLifestone", 1180),
            ("YouSuccessfullyLinkWithLifestone", 1181), ("YouMustLinkToLifestoneToRecall", 1182),
            ("YouFailToRecallToLifestone", 1183), ("YouFailToLinkWithPortal", 1184),
            ("YouSuccessfullyLinkWithPortal", 1185), ("YouFailToRecallToPortal", 1186),
            ("YouMustLinkToPortalToRecall", 1187), ("YouFailToSummonPortal", 1188),
            ("YouMustLinkToPortalToSummonIt", 1189), ("YouFailToTeleport", 1190),
            ("YouHaveBeenTeleportedTooRecently", 1191), ("YouMustBeAnAdvocateToUsePortal", 1192),
            ("PortalAisNotAllowed", 1193), ("PlayersMayNotUsePortal", 1194),
            ("YouAreNotPowerfulEnoughToUsePortal", 1195), ("YouAreTooPowerfulToUsePortal", 1196),
            ("YouCannotRecallPortal", 1197), ("YouCannotSummonPortal", 1198), ("LockAlreadyUnlocked", 1199),
            ("YouCannotLockOrUnlockThat", 1200), ("YouCannotLockWhatIsOpen", 1201), ("KeyDoesntFitThisLock", 1202),
            ("LockUsedTooRecently", 1203), ("YouArentTrainedInLockpicking", 1204), ("AllegianceInfoEmptyName", 1205),
            ("AllegianceInfoSelf", 1206), ("AllegianceInfoTooRecent", 1207), ("AbuseNoSuchCharacter", 1208),
            ("AbuseReportedSelf", 1209), ("AbuseComplaintHandled", 1210), ("YouDoNotOwnThatSalvageTool", 1213),
            ("YouDoNotOwnThatItem", 1214), ("MaterialCannotBeCreated", 1217),
            ("ItemsAttemptingToSalvageIsInvalid", 1218), ("YouCannotSalvageItemsInTrading", 1219),
            ("YouMustBeHouseGuestToUsePortal", 1220), ("YourAllegianceRankIsTooLowToUseMagic", 1221),
            ("YourArcaneLoreIsTooLowToUseMagic", 1223), ("ItemDoesntHaveEnoughMana", 1224),
            ("YouHaveBeenInPKBattleTooRecently", 1228), ("TradeAiRefuseEmote", 1229), ("YouFailToAlterSkill", 1232),
            ("FellowshipDeclined", 1243), ("FellowshipTimeout", 1244), ("YouHaveFailedToAlterAttributes", 1245),
            ("CannotTransferAttributesWhileWieldingItem", 1248), ("YouHaveSucceededTransferringAttributes", 1249),
            ("HookIsDuplicated", 1250), ("ItemIsWrongTypeForHook", 1251), ("HousingChestIsDuplicated", 1252),
            ("HookWillBeDeleted", 1253), ("HousingChestWillBeDeleted", 1254),
            ("CannotSwearAllegianceWhileOwningMansion", 1255), ("YouCantDoThatWhileInTheAir", 1259),
            ("CannotChangePKStatusWhileRecovering", 1260), ("AdvocatesCannotChangePKStatus", 1261),
            ("LevelTooLowToChangePKStatusWithObject", 1262), ("LevelTooHighToChangePKStatusWithObject", 1263),
            ("YouFeelAHarshDissonance", 1264), ("YouArePKAgain", 1265), ("YouAreTemporarilyNoLongerPK", 1266),
            ("PKLiteMayNotUsePortal", 1267), ("YouArentTrainedInHealing", 1276), ("YouDontOwnThatHealingKit", 1277),
            ("YouCantHealThat", 1278), ("YouArentReadyToHeal", 1280), ("YouCanOnlyHealPlayers", 1281),
            ("LifestoneMagicProtectsYou", 1282), ("PortalEnergyProtectsYou", 1283), ("YouAreNonPKAgain", 1284),
            ("YoureTooCloseToYourSanctuary", 1285), ("CantDoThatTradeInProgress", 1286),
            ("OnlyNonPKsMayEnterPKLite", 1287), ("YouAreNowPKLite", 1288), ("YouDoNotBelongToAFellowship", 1295),
            ("UsingMaxHooksSilent", 1297), ("YouAreNowUsingMaxHooks", 1298), ("YouAreNoLongerUsingMaxHooks", 1299),
            ("YouAreNotPermittedToUseThatHook", 1302), ("LockedFellowshipCannotRecruitYou", 1305),
            ("ActivationNotAllowedNotOwner", 1306), ("TurbineChatIsEnabled", 1309),
            ("YouCannotAddPeopleToHearList", 1312), ("YouAreNowDeafTo_Screams", 1315),
            ("YouCanHearAllPlayersOnceAgain", 1316), ("YouChickenOut", 1318), ("YouCanPossiblySucceed", 1319),
            ("FellowshipIsLocked", 1320), ("TradeComplete", 1321), ("NotASalvageTool", 1322),
            ("CharacterNotAvailable", 1323), ("YouMustWaitToPurchaseHouse", 1330),
            ("YouDoNotHaveAuthorityInAllegiance", 1333), ("YouHaveMaxAccountsBanned", 1344),
            ("YouHaveMaxAllegianceOfficers", 1349), ("YourAllegianceOfficersHaveBeenCleared", 1350),
            ("YouCannotJoinChannelsWhileGagged", 1352), ("YouAreNoLongerAllegianceOfficer", 1354),
            ("YourAllegianceDoesNotHaveHometown", 1356), ("HookItemNotUsable_CannotOpen", 1358),
            ("HookItemNotUsable_CanOpen", 1359), ("MissileOutOfRange", 1360),
            ("MustPurchaseThroneOfDestinyToUseFunction", 1362), ("MustPurchaseThroneOfDestinyToUseItem", 1363),
            ("MustPurchaseThroneOfDestinyToUsePortal", 1364), ("MustPurchaseThroneOfDestinyToAccessQuest", 1365),
            ("YouFailedToCompleteAugmentation", 1366), ("AugmentationUsedTooManyTimes", 1367),
            ("AugmentationTypeUsedTooManyTimes", 1368), ("AugmentationNotEnoughExperience", 1369),
            ("ExitTrainingAcademyToUseCommand", 1373), ("OnlyPKsMayUseCommand", 1375),
            ("OnlyPKLiteMayUseCommand", 1376), ("MaxFriendsExceeded", 1377),
            ("ThatCharacterNotOnYourFriendsList", 1379), ("OnlyHouseOwnerCanUseCommand", 1380),
            ("InvalidAllegianceNameCantBeEmpty", 1381), ("InvalidAllegianceNameTooLong", 1382),
            ("InvalidAllegianceNameBadCharacters", 1383), ("InvalidAllegianceNameInappropriate", 1384),
            ("InvalidAllegianceNameAlreadyInUse", 1385), ("AllegianceNameCleared", 1387),
            ("InvalidAllegianceNameSameName", 1388), ("InvalidOfficerLevel", 1391),
            ("AllegianceOfficerTitleIsNotAppropriate", 1392), ("AllegianceNameIsTooLong", 1393),
            ("AllegianceOfficerTitlesCleared", 1394), ("AllegianceTitleHasIllegalChars", 1395),
            ("YouHaveNotPreApprovedVassals", 1401), ("YouHaveClearedPreApprovedVassal", 1404),
            ("CharIsAlreadyGagged", 1405), ("CharIsNotCurrentlyGagged", 1406),
            ("YourAllegianceChatPrivilegesRestored", 1409), ("TooManyUniqueItems", 1412),
            ("HeritageRequiresSpecificArmor", 1413), ("ArmorRequiresSpecificHeritage", 1414),
            ("OlthoiCannotInteractWithThat", 1415), ("OlthoiCannotUseLifestones", 1416),
            ("OlthoiVendorLooksInHorror", 1417), ("OlthoiCannotJoinFellowship", 1419),
            ("OlthoiCannotJoinAllegiance", 1420), ("YouCannotUseThatItem", 1421),
            ("ThisPersonWillNotInteractWithYou", 1422), ("OnlyOlthoiMayUsePortal", 1423),
            ("OlthoiMayNotUsePortal", 1424), ("YouMayNotUsePortalWithVitae", 1425),
            ("YouMustBeTwoWeeksOldToUsePortal", 1426), ("OlthoiCanOnlyRecallToLifestone", 1427),
            ("ContractError", 1428),
        }),
        ("WeenieType", false, new (string, long)[]
        {
            ("Undef", 0), ("Generic", 1), ("Clothing", 2), ("MissileLauncher", 3), ("Missile", 4), ("Ammunition", 5),
            ("MeleeWeapon", 6), ("Portal", 7), ("Book", 8), ("Coin", 9), ("Creature", 10), ("Admin", 11),
            ("Vendor", 12), ("HotSpot", 13), ("Corpse", 14), ("Cow", 15), ("AI", 16), ("Machine", 17), ("Food", 18),
            ("Door", 19), ("Chest", 20), ("Container", 21), ("Key", 22), ("Lockpick", 23), ("PressurePlate", 24),
            ("LifeStone", 25), ("Switch", 26), ("PKModifier", 27), ("Healer", 28), ("LightSource", 29),
            ("Allegiance", 30), ("UNKNOWN__GUESSEDNAME32", 31), ("SpellComponent", 32), ("ProjectileSpell", 33),
            ("Scroll", 34), ("Caster", 35), ("Channel", 36), ("ManaStone", 37), ("Gem", 38), ("AdvocateFane", 39),
            ("AdvocateItem", 40), ("Sentinel", 41), ("GSpellEconomy", 42), ("LSpellEconomy", 43), ("CraftTool", 44),
            ("LScoreKeeper", 45), ("GScoreKeeper", 46), ("GScoreGatherer", 47), ("ScoreBook", 48),
            ("EventCoordinator", 49), ("Entity", 50), ("Stackable", 51), ("HUD", 52), ("House", 53), ("Deed", 54),
            ("SlumLord", 55), ("Hook", 56), ("Storage", 57), ("BootSpot", 58), ("HousePortal", 59), ("Game", 60),
            ("GamePiece", 61), ("SkillAlterationDevice", 62), ("AttributeTransferDevice", 63), ("Hooker", 64),
            ("AllegianceBindstone", 65), ("InGameStatKeeper", 66), ("AugmentationDevice", 67), ("SocialManager", 68),
            ("Pet", 69), ("PetDevice", 70), ("CombatPet", 71),
        }),
        ("WieldType", true, new (string, long)[]
        {
            ("Invalid", 0), ("MeleeWeapon", 1), ("Armor", 2), ("Clothing", 4), ("Jewelry", 8),
        }),
        ("AddRemoveEventType", false, new (string, long)[]
        {
            ("Added", 0), ("Removed", 1),
        }),
        ("BusyAction", false, new (string, long)[]
        {
            ("None", 0), ("Crafting", 1), ("Wielding", 2), ("SpellCasting", 4), ("OpeningTrade", 8),
            ("DroppingWeenie", 16), ("GivingWeenie", 32), ("LoggingOut", 64), ("MovingWeenie", 128),
            ("UsingWeenie", 256), ("MovingWeenieToContainer", 512), ("TeleToLifestone", 1024), ("Portalling", 2048),
            ("Animating", 4096), ("ChangeCombatMode", 8192), ("TeleToMarketplace", 16384), ("TeleToPKArena", 32768),
            ("AdvocateTeleport", 65536), ("TeleToHouse", 131072), ("TeleToMansion", 262144),
            ("TeleToAllegianceHometown", 524288), ("RecallCommand", 1033216),
        }),
        ("CastEventType", false, new (string, long)[]
        {
            ("Untargetted", 0), ("Targetted", 1),
        }),
        ("ChatChannel", false, new (string, long)[]
        {
            ("None", 0), ("Allegiance", 1), ("General", 2), ("Trade", 3), ("LFG", 4), ("Roleplay", 5), ("Olthoi", 6),
            ("Society", 7), ("CelestialHand", 8), ("EldrytchWeb", 9), ("RadiantBlood", 10),
        }),
        ("ClientCapability", false, new (string, long)[]
        {
            ("ImGui", 1),
        }),
        ("ClientConfirmationType", false, new (string, long)[]
        {
            ("UNDEF", 0), ("ALLEGIANCE_SWEAR", 1), ("ALTER_SKILL", 2), ("ALTER_ATTRIBUTE", 3),
            ("FELLOWSHIP_RECRUIT", 4), ("CRAFT_INTERACTION", 5), ("USE_AUGMENTATION", 6), ("YESNO", 7),
        }),
        ("DistanceType", false, new (string, long)[]
        {
            ("T2D", 0), ("T3D", 1),
        }),
        ("FellowshipEventType", false, new (string, long)[]
        {
            ("Create", 0), ("Quit", 1), ("Dismiss", 2), ("Recruit", 3), ("Disband", 4),
        }),
        ("ScriptStartupType", false, new (string, long)[]
        {
            ("Manual", 0), ("Global", 1), ("Account", 2), ("Character", 3),
        }),
        ("UseActionType", false, new (string, long)[]
        {
            ("Default", 0), ("Vendor", 1), ("SummonPortal", 2), ("Portal", 3),
        }),
    };
}
