---@meta enums
-- Editor definitions for require("enums") (RynthLua). Not loaded in the game.
-- The same tables are globals in every script.

return {
    ObjectClass = ObjectClass,
    SkillId = SkillId,
    AttributeId = AttributeId,
    VitalId = VitalId,
    CombatMode = CombatMode,
    IntId = IntId,
    BoolId = BoolId,
    StringId = StringId,
    ChatType = ChatType,
    AmmoType = AmmoType,
    AttackHeight = AttackHeight,
    CharacterOptions1 = CharacterOptions1,
    CharacterOptions2 = CharacterOptions2,
    ContainerProperties = ContainerProperties,
    CoverageMask = CoverageMask,
    CreatureType = CreatureType,
    DamageType = DamageType,
    DataId = DataId,
    EnchantmentFlags = EnchantmentFlags,
    EndTradeReason = EndTradeReason,
    EquipMask = EquipMask,
    FloatId = FloatId,
    Gender = Gender,
    HeritageGroup = HeritageGroup,
    IconHighlight = IconHighlight,
    InstanceId = InstanceId,
    Int64Id = Int64Id,
    MagicSchool = MagicSchool,
    MaterialType = MaterialType,
    MotionStance = MotionStance,
    ObjectDescriptionFlag = ObjectDescriptionFlag,
    ObjectType = ObjectType,
    PhysicsState = PhysicsState,
    PlayScript = PlayScript,
    RadarBehavior = RadarBehavior,
    RadarColor = RadarColor,
    SkillTrainingType = SkillTrainingType,
    SpellCategory = SpellCategory,
    SpellFlags = SpellFlags,
    SpellType = SpellType,
    TradeSide = TradeSide,
    UsableType = UsableType,
    Vital = Vital,
    WeenieError = WeenieError,
    WeenieType = WeenieType,
    WieldType = WieldType,
    AddRemoveEventType = AddRemoveEventType,
    BusyAction = BusyAction,
    CastEventType = CastEventType,
    ChatChannel = ChatChannel,
    ClientCapability = ClientCapability,
    ClientConfirmationType = ClientConfirmationType,
    DistanceType = DistanceType,
    FellowshipEventType = FellowshipEventType,
    ScriptStartupType = ScriptStartupType,
    UseActionType = UseActionType,
    ChatMessageType = ChatMessageType,
    ClientState = ClientState,
}
